# Generated by Django 5.0 on 2024-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('image8', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
