# Generated by Django 5.0 on 2024-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_lunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image9', models.ImageField(upload_to='images/')),
                ('image10', models.ImageField(upload_to='images/')),
                ('image11', models.ImageField(upload_to='images/')),
                ('image12', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image13', models.ImageField(upload_to='images/')),
                ('image14', models.ImageField(upload_to='images/')),
                ('image15', models.ImageField(upload_to='images/')),
                ('image16', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
