# Generated by Django 5.0 on 2024-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_breakfirst_dinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('tital', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('para1', models.CharField(max_length=300)),
                ('para2', models.CharField(max_length=300)),
            ],
        ),
    ]
