# Generated by Django 5.0 on 2024-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('p', 'person1'), ('p1', 'person2'), ('p2', 'person3'), ('p3', 'person4')], max_length=10, verbose_name='person')),
            ],
        ),
        migrations.DeleteModel(
            name='BreakFirst',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
        migrations.DeleteModel(
            name='special',
        ),
    ]
