# Generated by Django 5.0 on 2024-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_dropdown_delete_breakfirst_delete_dinner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=50, verbose_name='Student First Name')),
                ('student_last_name', models.CharField(max_length=50, verbose_name='Student Last Name')),
                ('student_date_of_birth', models.DateField(verbose_name='Student Date Of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
    ]
