# Generated by Django 5.0 on 2024-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_studentprofile_testmodel_delete_dropdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('cont1', models.CharField(max_length=30)),
                ('paragraph', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='datemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
            ],
        ),
    ]
