# Generated by Django 5.0 on 2024-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_blog1_datemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('cont2', models.CharField(max_length=30)),
                ('paragraph2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='blog3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('cont3', models.CharField(max_length=30)),
                ('paragraph3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='blog4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image4', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('cont4', models.CharField(max_length=30)),
                ('paragraph4', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='blog5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image5', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('cont5', models.CharField(max_length=30)),
                ('paragraph5', models.CharField(max_length=300)),
            ],
        ),
    ]
